### ISSUE TITLE
config ip setting is not respected

### ISSUE THREAD

**Issue by szarouski** [hexojs/hexo-server#6]
In my config file I have following:
```YAML
port: 4000
server_ip: 127.0.0.1
```

However hexo always starts on `0.0.0.0`. For now I use --ip as a workaround, and I think it should be fixed.

**Comment by tommy351** [comment]
Try this:

``` yml
server:
  ip: 127.0.0.1
  port: 4000
```
